# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 669)
        MainWindow.setStyleSheet("background-color: rgb(10, 25, 30);\n"
"color:rgb(200,200,200);\n"
"border-color:rgb(200,200,200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.searchgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.searchgroupBox.setObjectName("searchgroupBox")
        self.gridLayout.addWidget(self.searchgroupBox, 2, 0, 1, 1)
        self.articlesgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.articlesgroupBox.setObjectName("articlesgroupBox")
        self.gridLayout.addWidget(self.articlesgroupBox, 3, 0, 1, 1)
        self.previewgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.previewgroupBox.setObjectName("previewgroupBox")
        self.gridLayout.addWidget(self.previewgroupBox, 3, 1, 1, 1)
        self.groupsgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupsgroupBox.setObjectName("groupsgroupBox")
        self.gridLayout.addWidget(self.groupsgroupBox, 2, 1, 1, 1)
        self.statisticsgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statisticsgroupBox.setObjectName("statisticsgroupBox")
        self.gridLayout.addWidget(self.statisticsgroupBox, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Readticle"))
        self.searchgroupBox.setTitle(_translate("MainWindow", "Search and Add"))
        self.articlesgroupBox.setTitle(_translate("MainWindow", "Articles"))
        self.previewgroupBox.setTitle(_translate("MainWindow", "Preview"))
        self.groupsgroupBox.setTitle(_translate("MainWindow", "Groups"))
        self.statisticsgroupBox.setTitle(_translate("MainWindow", "Statistisc"))
